### ISSUE TITLE
Cannot build LazyMe

### ISSUE THREAD

**Issue by carlca** [UjjwalAyyangar/LazyMe#2]
Go 1.11 rc1
macOS 10.13.6

> Thanks for the email. Have you tried installing Go Dep and performing "dep ensure" ?
> 
> Also, thanks for pointing out about not being able to open issues in my repository (I forgot to  enable it. Slipped my mind :|). I have enabled it now. Let me know if "dep ensure" works out for you and open an issue on Github if it doesn't.
> 

Thanks for the reply! I haven’t tried `Go Dep` because I am trying to standardise on `Go Modules` for my dependancy manager needs. I guess there’ nothing to stop me running `Go Dep` on this one package, though.

Hang on a second…

I’ve used `brew` to install `Go Dep`. I then switched `go modules` off, installed `lazyme` using `go get github.com/UjjwalAyyangar/lazyme` and finally ran `dep ensure` within the `lazyme` folder. I didn’t get any error messages so I assume it worked. I still cannot run `lazyme`. What next??!!

**Comment by carlca** [comment]
After running `GO111MODULE=on go build ./...`
```
go: creating new go.mod: module github.com/UjjwalAyyangar/lazyme
go: copying requirements from Gopkg.lock
go: finding github.com/google/go-github v16.0.0+incompatible
go: finding github.com/google/go-querystring v0.0.0-20170111101155-53e6ce116135
go: finding golang.org/x/sys v0.0.0-20180808154034-904bdc257025
go: finding golang.org/x/crypto v0.0.0-20180808211826-de0752318171
go: downloading golang.org/x/crypto v0.0.0-20180808211826-de0752318171
go: downloading github.com/google/go-github v16.0.0+incompatible
go: downloading github.com/google/go-querystring v0.0.0-20170111101155-53e6ce116135
go: downloading golang.org/x/sys v0.0.0-20180808154034-904bdc257025
build github.com/UjjwalAyyangar/lazyme: cannot find module for path LazyMe/lazy
``` 

Afte running ` GO111MODULE=off go build ./...`
```
create.go:4:2: cannot find package "LazyMe/lazy" in any of:
	/usr/local/go/src/LazyMe/lazy (from $GOROOT)
	/Users/carlca/Code/go/src/LazyMe/lazy (from $GOPATH)
```

Either way, with or without Go Modules, I cannot get LazyMe to build.

**Comment by shubhodeep9** [comment]
Hi @carlca 
thanks for creating the issue,
I am on it. I will reply on this thread as soon as it gets done.

**Comment by shubhodeep9** [comment]
Hi @carlca please try now.
Inform if another issue exists.
Cheers

**Comment by carlca** [comment]
Hello, @shubhodeep9 I was able to `git clone` the latest with `GO111MODULE=on` and this time, I was able to run `go install ./...` successfully, and now it runs! Thanks very much for your help!
